name: BETA Release
on:
  push:
    branches:
      - beta
  workflow_dispatch:

env:
  PACKAGE_NAME: 'fm-localized'
  MS_URL: 'https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-front-matter-beta'
  VSX_URL: 'https://open-vsx.org/extension/eliostruyf/vscode-front-matter-beta'

jobs:
  localization:
    name: 'Localization'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Localize the solution
        uses: ./.github/actions/localization
        with:
          TRANSLATION_API_KEY: ${{ secrets.TRANSLATION_API_KEY }}
          TRANSLATION_API_LOCATION: ${{ secrets.TRANSLATION_API_LOCATION }}
          TRANSLATION_API_URL: ${{ secrets.TRANSLATION_API_URL }}
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}

  release-ms:
    name: 'Release to VSCode Marketplace'
    runs-on: ubuntu-latest
    needs: localization
    environment:
      name: 'MS - BETA'
      url: ${{ env.MS_URL }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install the dependencies
        run: npm ci

      - name: Prepare BETA
        run: node scripts/beta-release.js $GITHUB_RUN_ID

      - name: Publish
        run: npx @vscode/vsce publish -p ${{ secrets.VSCE_PAT }} --baseImagesUrl https://raw.githubusercontent.com/estruyf/vscode-front-matter/dev

  release-vsx:
    name: 'Release to Open VSX'
    runs-on: ubuntu-latest
    needs: localization
    environment:
      name: 'Open VSX - BETA'
      url: ${{ env.VSX_URL }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install the dependencies
        run: npm ci

      - name: Prepare BETA
        run: node scripts/beta-release.js $GITHUB_RUN_ID

      - name: Publish to open-vsx.org
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_PAT }}
